/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Nov 17 23:31:13 GMT 2018
 */

package uMer;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class ATS_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "uMer.ATS"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/xv/9zh5ycls6zq08d5j_54vpnp00000gn/T/"); 
    java.lang.System.setProperty("user.country", "PT"); 
    java.lang.System.setProperty("user.dir", "/Users/dianalopes/Desktop/Imprimir/UMeRTesting"); 
    java.lang.System.setProperty("user.home", "/Users/dianalopes"); 
    java.lang.System.setProperty("user.language", "pt"); 
    java.lang.System.setProperty("user.name", "dianalopes"); 
    java.lang.System.setProperty("user.timezone", "Europe/Lisbon"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ATS_ESTest_scaffolding.class.getClassLoader() ,
      "org.antlr.v4.runtime.tree.SyntaxTree",
      "org.antlr.v4.runtime.tree.RuleNode",
      "uMer.ATSParser$LogContext",
      "org.antlr.v4.runtime.atn.NotSetTransition",
      "org.antlr.v4.runtime.ANTLRErrorStrategy",
      "org.antlr.v4.runtime.Token",
      "org.antlr.v4.runtime.atn.ATNState",
      "uMer.ATSParser$RegistarcondutorContext",
      "uMer.ATSParser$RegistarclienteContext",
      "uMer.ATSParser$RecusarviagemContext",
      "org.antlr.v4.runtime.CharStreams",
      "org.antlr.v4.runtime.atn.LoopEndState",
      "org.antlr.v4.runtime.atn.PlusBlockStartState",
      "org.antlr.v4.runtime.IntStream",
      "uMer.User",
      "org.antlr.v4.runtime.atn.AbstractPredicateTransition",
      "org.antlr.v4.runtime.misc.IntSet",
      "org.antlr.v4.runtime.misc.Utils",
      "org.antlr.v4.runtime.CodePointCharStream",
      "org.antlr.v4.runtime.Recognizer",
      "org.antlr.v4.runtime.misc.IntegerList",
      "org.antlr.v4.runtime.CodePointBuffer$1",
      "uMer.Bike",
      "org.antlr.v4.runtime.atn.PredicateTransition",
      "org.antlr.v4.runtime.tree.TerminalNode",
      "org.antlr.v4.runtime.atn.RuleStartState",
      "org.antlr.v4.runtime.atn.ATNSimulator",
      "org.antlr.v4.runtime.atn.EmptyPredictionContext",
      "uMer.ATSParser$FiabilidadeContext",
      "uMer.ATSParser$CoordxContext",
      "uMer.ATSParser$AcaoContext",
      "org.antlr.v4.runtime.ParserRuleContext",
      "uMer.Vehicle",
      "org.antlr.v4.runtime.tree.ErrorNode",
      "uMer.ATSParser$PasswordContext",
      "org.antlr.v4.runtime.atn.TokensStartState",
      "uMer.UMeR",
      "org.antlr.v4.runtime.atn.DecisionState",
      "org.antlr.v4.runtime.misc.Predicate",
      "uMer.ATSParser$RegistarHelicopteroContext",
      "org.antlr.v4.runtime.atn.BlockEndState",
      "uMer.ATSParser$FatorCumpContext",
      "uMer.ATSParser$MoradaContext",
      "uMer.ATSParser$NomeContext",
      "org.antlr.v4.runtime.CodePointBuffer$Type",
      "org.antlr.v4.runtime.atn.EpsilonTransition",
      "org.antlr.v4.runtime.tree.Trees",
      "org.antlr.v4.runtime.atn.ActionTransition",
      "org.antlr.v4.runtime.RuleContext",
      "org.antlr.v4.runtime.CharStream",
      "uMer.ATSParser$DonoContext",
      "uMer.Helicopter",
      "org.antlr.v4.runtime.tree.ParseTree",
      "org.antlr.v4.runtime.atn.ParserATNSimulator",
      "uMer.Trip",
      "org.antlr.v4.runtime.atn.ProfilingATNSimulator",
      "uMer.Van",
      "org.antlr.v4.runtime.atn.AtomTransition",
      "org.antlr.v4.runtime.TokenSource",
      "uMer.Client",
      "org.antlr.v4.runtime.atn.ATNDeserializationOptions",
      "org.antlr.v4.runtime.RecognitionException",
      "org.antlr.v4.runtime.CodePointCharStream$1",
      "org.antlr.v4.runtime.Parser",
      "org.antlr.v4.runtime.atn.LexerAction",
      "org.antlr.v4.runtime.tree.ParseTreeListener",
      "org.antlr.v4.runtime.atn.RangeTransition",
      "uMer.ATSParser$EmailContext",
      "uMer.ATSParser$CoordyContext",
      "org.antlr.v4.runtime.VocabularyImpl",
      "org.antlr.v4.runtime.CodePointBuffer",
      "org.antlr.v4.runtime.ANTLRErrorListener",
      "org.antlr.v4.runtime.atn.WildcardTransition",
      "org.antlr.v4.runtime.misc.Interval",
      "uMer.ATSParser$RegistarcarrinhaContext",
      "org.antlr.v4.runtime.TokenStream",
      "org.antlr.v4.runtime.atn.StarLoopbackState",
      "uMer.ATSParser$SessaoContext",
      "org.antlr.v4.runtime.atn.RuleTransition",
      "uMer.ATSParser$LoginContext",
      "org.antlr.v4.runtime.tree.ParseTreeVisitor",
      "org.antlr.v4.runtime.Lexer",
      "uMer.ATSParser$RegistarveiculoContext",
      "uMer.ATSParser$RegistarcarroContext",
      "uMer.ATSParser$PosicaoContext",
      "org.antlr.v4.runtime.atn.PrecedencePredicateTransition",
      "org.antlr.v4.runtime.CodePointBuffer$Builder",
      "org.antlr.v4.runtime.TokenFactory",
      "org.antlr.v4.runtime.atn.SingletonPredictionContext",
      "org.antlr.v4.runtime.atn.StarBlockStartState",
      "org.antlr.v4.runtime.tree.Tree",
      "org.antlr.v4.runtime.Vocabulary",
      "uMer.Car",
      "org.antlr.v4.runtime.atn.BasicBlockStartState",
      "org.antlr.v4.runtime.atn.PredictionContext",
      "uMer.ATSParser$RegistarmotaContext",
      "org.antlr.v4.runtime.atn.PlusLoopbackState",
      "org.antlr.v4.runtime.misc.IntervalSet",
      "uMer.ATSParser$NomeEmpresaContext",
      "uMer.ATSParser$RegistarempresaContext",
      "org.antlr.v4.runtime.atn.PredictionContextCache",
      "org.antlr.v4.runtime.atn.BasicState",
      "org.antlr.v4.runtime.NoViableAltException",
      "org.antlr.v4.runtime.RuntimeMetaData",
      "uMer.ATSParser$LogoutContext",
      "org.antlr.v4.runtime.atn.ParseInfo",
      "org.antlr.v4.runtime.atn.Transition",
      "org.antlr.v4.runtime.atn.ATNDeserializer",
      "uMer.ATSParser$ViajarContext",
      "uMer.ATS",
      "uMer.ATSParser",
      "uMer.ATSParser$SolicitarContext",
      "org.antlr.v4.runtime.atn.ATNDeserializer$UnicodeDeserializer",
      "org.antlr.v4.runtime.atn.SetTransition",
      "uMer.ATSParser$MatriculaContext",
      "org.antlr.v4.runtime.tree.pattern.ParseTreePattern",
      "org.antlr.v4.runtime.atn.RuleStopState",
      "uMer.Driver",
      "org.antlr.v4.runtime.atn.ATN",
      "org.antlr.v4.runtime.atn.StarLoopEntryState",
      "uMer.ATSParser$RegistarContext",
      "org.antlr.v4.runtime.atn.BlockStartState",
      "uMer.ATSParser$DataContext"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ATS_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "uMer.ATS",
      "org.antlr.v4.runtime.ParserRuleContext",
      "org.antlr.v4.runtime.RuleContext",
      "org.antlr.v4.runtime.CodePointBuffer$Type",
      "org.antlr.v4.runtime.CodePointCharStream$1",
      "uMer.UMeR",
      "org.antlr.v4.runtime.CharStreams",
      "org.antlr.v4.runtime.CodePointBuffer",
      "org.antlr.v4.runtime.CodePointBuffer$Builder",
      "org.antlr.v4.runtime.CodePointBuffer$1",
      "uMer.ATSParser$LogoutContext",
      "uMer.ATSParser$LogContext",
      "uMer.ATSParser$LoginContext",
      "uMer.ATSParser$RegistarveiculoContext",
      "uMer.ATSParser$FiabilidadeContext",
      "uMer.ATSParser$SolicitarContext",
      "uMer.ATSParser$PasswordContext",
      "uMer.ATSParser$NomeContext",
      "uMer.ATSParser$NomeEmpresaContext",
      "uMer.ATSParser$AcaoContext",
      "uMer.ATSParser$CoordxContext",
      "uMer.ATSParser$RegistarcarrinhaContext",
      "uMer.ATSParser$PosicaoContext",
      "uMer.ATSParser$RegistarempresaContext",
      "uMer.ATSParser$RegistarContext",
      "uMer.ATSParser$RegistarclienteContext",
      "uMer.ATSParser$RegistarcarroContext",
      "uMer.ATSParser$RegistarmotaContext",
      "uMer.ATSParser$EmailContext",
      "uMer.ATSParser$RegistarHelicopteroContext",
      "uMer.ATSParser$MoradaContext",
      "uMer.ATSParser$DonoContext",
      "uMer.ATSParser$FatorCumpContext",
      "uMer.ATSParser$MatriculaContext",
      "uMer.ATSParser$RecusarviagemContext",
      "uMer.ATSParser$SessaoContext",
      "uMer.ATSParser$DataContext",
      "uMer.ATSParser$RegistarcondutorContext",
      "org.antlr.v4.runtime.Recognizer",
      "org.antlr.v4.runtime.Parser",
      "org.antlr.v4.runtime.tree.Trees",
      "org.antlr.v4.runtime.misc.Utils",
      "uMer.ATSParser$ViajarContext",
      "uMer.ATSParser$CoordyContext",
      "org.antlr.v4.runtime.misc.Interval"
    );
  }
}
