/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 17 23:26:49 GMT 2018
 */

package uMer;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.util.HashMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import uMer.Car;
import uMer.Trip;
import uMer.Vehicle;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Car_ESTest extends Car_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Car car0 = new Car("", 0.0, point2D_Double0, "");
      Car car1 = car0.clone();
      assertEquals(65.0, car0.getSpeed(), 0.01);
      assertEquals(65.0, car1.getSpeed(), 0.01);
      assertEquals(4, car1.getSeats());
      assertEquals(4, car0.getSeats());
      assertEquals(1.5, car0.getPrice(), 0.01);
      assertEquals(1.5, car1.getPrice(), 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Car car0 = new Car("|#)*=:swDeI)5(eU6q", (-743.05), point2D_Double0, "|#)*=:swDeI)5(eU6q");
      Car car1 = car0.clone();
      assertEquals(65.0, car1.getSpeed(), 0.01);
      assertEquals(65.0, car0.getSpeed(), 0.01);
      assertEquals(1.5, car0.getPrice(), 0.01);
      assertEquals(4, car1.getSeats());
      assertEquals(4, car0.getSeats());
      assertEquals(1.5, car1.getPrice(), 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Car car0 = new Car("\n\n", 381.2, point2D_Double0, "BaTE8");
      Trip trip0 = new Trip();
      car0.addTrip(trip0);
      // Undeclared exception!
      try { 
        car0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uMer.Trip", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Point2D.Double point2D_Double0 = mock(Point2D.Double.class, new ViolatedAssumptionAnswer());
      doReturn(0.0).when(point2D_Double0).getX();
      doReturn(0.0).when(point2D_Double0).getY();
      Car car0 = new Car("", 1.9, point2D_Double0, "m`fgtW2F_");
      // Undeclared exception!
      try { 
        car0.calculateTraffic((HashMap<String, Vehicle>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uMer.Car", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Car car0 = null;
      try {
        car0 = new Car("", 0.0, (Point2D.Double) null, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uMer.Vehicle", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double(0.0, 0.0);
      Car car0 = new Car(">b", 0.0, point2D_Double0, "<~>|R");
      Car car1 = new Car(car0);
      assertEquals(4, car0.getSeats());
      assertEquals(4, car1.getSeats());
      assertEquals(1.5, car0.getPrice(), 0.01);
      assertEquals(65.0, car1.getSpeed(), 0.01);
      assertEquals(1.5, car1.getPrice(), 0.01);
      assertEquals(65.0, car0.getSpeed(), 0.01);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Point2D.Double point2D_Double0 = mock(Point2D.Double.class, new ViolatedAssumptionAnswer());
      doReturn(0.0).when(point2D_Double0).getX();
      doReturn(0.0).when(point2D_Double0).getY();
      Car car0 = new Car("", 1.9, point2D_Double0, "m`fgtW2F_");
      Car car1 = car0.clone();
      assertEquals(65.0, car1.getSpeed(), 0.01);
      assertEquals(4, car0.getSeats());
      assertEquals(1.5, car0.getPrice(), 0.01);
      assertEquals(65.0, car0.getSpeed(), 0.01);
      assertEquals(4, car1.getSeats());
      assertEquals(1.5, car1.getPrice(), 0.01);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Car car0 = null;
      try {
        car0 = new Car((Car) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uMer.Car", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Car car0 = null;
      try {
        car0 = new Car();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
