/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 17 23:24:25 GMT 2018
 */

package uMer;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import uMer.DeviationComparator;
import uMer.Driver;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DeviationComparator_ESTest extends DeviationComparator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DeviationComparator deviationComparator0 = new DeviationComparator();
      Driver driver0 = mock(Driver.class, new ViolatedAssumptionAnswer());
      doReturn(28.14986, 974.6, 28.14986, 28.14986).when(driver0).getDeviation();
      doReturn(";I(l5?@x<F.", ";I(l5?@x<F.").when(driver0).getEmail();
      int int0 = deviationComparator0.compare(driver0, driver0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DeviationComparator deviationComparator0 = new DeviationComparator();
      Driver driver0 = mock(Driver.class, new ViolatedAssumptionAnswer());
      doReturn(0.0, 0.0, 346.8324727678506, 0.0).when(driver0).getDeviation();
      doReturn("uMer.DeviationComparator", "uMer.DeviationComparator").when(driver0).getEmail();
      int int0 = deviationComparator0.compare(driver0, driver0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DeviationComparator deviationComparator0 = new DeviationComparator();
      Driver driver0 = mock(Driver.class, new ViolatedAssumptionAnswer());
      doReturn(3222.7375575642, 3222.7375575642, (-1.0), 802.15).when(driver0).getDeviation();
      int int0 = deviationComparator0.compare(driver0, driver0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DeviationComparator deviationComparator0 = new DeviationComparator();
      Driver driver0 = mock(Driver.class, new ViolatedAssumptionAnswer());
      doReturn(346.8324727678506, (double)1).when(driver0).getDeviation();
      int int0 = deviationComparator0.compare(driver0, driver0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DeviationComparator deviationComparator0 = new DeviationComparator();
      Driver driver0 = mock(Driver.class, new ViolatedAssumptionAnswer());
      doReturn(0.0).when(driver0).getDeviation();
      doReturn((String) null).when(driver0).getEmail();
      Driver driver1 = mock(Driver.class, new ViolatedAssumptionAnswer());
      doReturn(0.0, 0.0, 0.0).when(driver1).getDeviation();
      doReturn((String) null).when(driver1).getEmail();
      // Undeclared exception!
      try { 
        deviationComparator0.compare(driver0, driver1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uMer.DeviationComparator", e);
      }
  }
}
